name: CI

on: [push, pull_request]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pipenv"
          cache-dependency-path: Pipfile.lock
      - name: Install pipenv
        run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
      - name: Install Dependencies
        run: |
          pipenv --version
          pipenv install --deploy --system --dev
      - name: flake8
        run: flake8
      - name: pylint
        run: pylint src
      - name: mypy
        run: mypy src
  analysis:
    name: Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pipenv"
          cache-dependency-path: Pipfile.lock
      - name: Install pipenv
        run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
      - name: Install Dependencies
        run: |
          pipenv --version
          pipenv install --deploy --system --dev
      - name: bandit
        run: bandit -r src
      - name: ochrona
        run: ochrona
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pipenv"
          cache-dependency-path: Pipfile.lock
      - name: Install pipenv
        run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
      - name: Install Dependencies
        run: |
          pipenv --version
          pipenv install --deploy --system --dev
      - name: Tests
        run: pytest -vv --cov-report=xml --cov=src tests/
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          files: ./coverage.xml
          flags: unittest
          verbose: true